# This composer will only work for machines running on Intel x86 architecture
# For any other device, we recommend either running the remote docker image or
# installing the virtual environment with the files provided.
services:
  hotdog_predictor:
    image: jentsang/hotdog-predictor:latest  
    container_name: hotdog_predictor
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/dog_or_not
    working_dir: /home/dog_or_not
    stdin_open: true
    tty: true