# This composer will only work for machines running on Intel x86 architecture
# For any other device, we recommend either running the remote docker image or
# installing the virtual environment with the files provided.
services:
  hotdog_predictor:
    build:
      context: .
      dockerfile: Dockerfile
    image: hotdog_predictor
    container_name: hotdog_predictor
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true