services:
  hotdog_predictor:
    image: jentsang/hotdog-predictor:sha-561dde5  
    container_name: hotdog_predictor
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/dog_or_not
    working_dir: /home/dog_or_not
    stdin_open: true
    tty: true