name: dsci522proj
channels:
  - conda-forge
dependencies:
  - python=3.11
  - conda-lock=3.0.4
  - scikit-learn=1.7.2
  - pandas=2.3.3
  - jupyterlab=4.4.10
  - altair=6.0.0
  - matplotlib=3.10.7
  - pip=25.3
  - pandera=0.26.1
  - pip:
    - mglearn==0.2.0